### ISSUE TITLE
How to get dynamically created jobs

### ISSUE THREAD

**Issue by debugger22m** [farhan711/task-scheduling#1]
Hi Farhan,

Thanks for referring me to your repo, I find it easier to understand. However, I have a quick question about getting jobs list. 

I'm creating jobs dynamically and saving them in the database. How do I retrieve those jobs and process them here. 

Referring to your comments.
```
// if you are adding the job types dynamically and saving them in the database you will get it here
let jobTypes = ["emailSchedule"];
```

Thanks!

**Comment by farhan711** [comment]
Hello @120bits if you're creating it dynamically then you must use `agenda.define('YourParamerForJob')` something like this. And in job types, you have to follow the existing structure. Only now the jobs you create would be manual. (Refer this section of the document - [here](https://github.com/agenda/agenda#manually-working-with-a-job))

I hope this would get your requirements.
